export const WP_REST_API_BASE_URL = "https://blog.debmedia.com/wp-json/wp/v2";
export const WP_GQL_API_BASE_URL = "https://blog.debmedia.com/graphql";
export const WP_POST_URL = "posts";
export const WEB_BASE_URL = "https://debmedia.com"
export const BLOG_ABSOLUTE_URL = "https://debmedia.com/blog";
export const BLOG_NEW_URL= "/blog-new"
export const BLOG_CATEGORIES_URL = BLOG_NEW_URL + "/categorias"
export const BLOG_NEWS_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/novedades"
export const BLOG_SUCCESS_STORIES_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/casos-de-exito"
export const BLOG_E_BOOKS_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/ebooks"
export const BLOG_NEWS_ARTICLES_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/noticias"
export const BLOG_PODCAST_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/podcast"
export const BLOG_BANKING_AND_INSURANCE_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/banca-y-seguros"
export const BLOG_INDUSTRIES_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/industrias"
export const BLOG_GOVERNMENT_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/gobierno"
export const BLOG_RETAIL_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/retail"
export const BLOG_HEALTH_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/salud"
export const BLOG_TELECOMUNICATIONS_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/telecomunicaciones"
export const BLOG_UTILITIES_CATEGORIES_URL = BLOG_CATEGORIES_URL + "/utilities"